# Generated by Django 4.0.1 on 2022-04-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareTakerInfo',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('number', models.CharField(max_length=10, verbose_name='Phone')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'O')], max_length=10, verbose_name='Gender')),
                ('adhar_num', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Adhaar')),
                ('bank_num', models.CharField(max_length=20, verbose_name='Bank Account')),
                ('Ed_q', models.CharField(choices=[('Mtriculate', 'M'), ('Intermediat', 'I'), ('Graduate', 'G')], max_length=50, verbose_name='Educational Qualifications')),
                ('exp', models.CharField(choices=[('0-2 Years', 'poor'), ('2-4 years', 'Intermediat'), ('4-6 Years', 'Good')], max_length=120, verbose_name='Experience')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('pin_code', models.CharField(max_length=7, verbose_name='Pincode')),
                ('city', models.CharField(max_length=50)),
                ('resume_drive', models.URLField(blank=True, verbose_name='Resume drive link')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics_caretaker')),
                ('password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='relative',
            fields=[
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Phone')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'O')], max_length=10, verbose_name='Gender')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('pin_code', models.CharField(max_length=7, verbose_name='Pincode')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('password', models.CharField(max_length=12)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics_relative')),
            ],
        ),
        migrations.CreateModel(
            name='senior_citizen',
            fields=[
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Phone')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'O')], max_length=10, verbose_name='Gender')),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('pin_code', models.CharField(max_length=7, verbose_name='Pincode')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics_senior')),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
